name: Trigger Call API

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  trigger_api:
    runs-on: ubuntu-latest
    env:
      DOMEINNAAM: ${{ secrets.DOMEINNAAM_ACC }}
      INLOG: ${{ secrets.INLOG }}
      WACHTWOORD: ${{ secrets.WACHTWOORD_ACC }}
      APP: ${{ secrets.APP }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
    steps:
      - name: Trigger Call
        run: |
          echo "Triggering API call at: https://${DOMEINNAAM-acc}/index.php/apps/${APP}${ENDPOINT_ACC}"
          curl -X POST -u "${INLOG}:${WACHTWOORD}" "https://${DOMEINNAAM-acc}/index.php/apps/${APP}${ENDPOINT_ACC}"
